# Generated by Django 2.0.8 on 2018-09-12 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=30)),
                ('Last_name', models.CharField(max_length=30)),
                ('Author', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=11)),
                ('address', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
