# Generated by Django 2.0.8 on 2018-09-12 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalexam', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='Author',
            new_name='author',
        ),
    ]
