# Generated by Django 2.0.8 on 2018-09-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalexam', '0002_auto_20180912_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=30)),
                ('Last_name', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=11)),
                ('address', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
